### ISSUE TITLE
Provide a brief overview of features & example usage in README

### ISSUE THREAD

**Issue by regexident** [Blackjacx/Columbus#2]
Hi Stefan, long time no see! 👋🏻😃

---

Columbus claims to be a full featured implementation, yet misses to actually list any features or snippets showing how to use it.

> A country picker for iOS, tvOS and watchOS with features you'll only find distributed in many different country-picker implementations.

**Comment by Blackjacx** [comment]
Hey Vincent ✋ 🙃

Oh yes of course! I know the start of a new lib should be a boom and everything should just be perfect. This gives the best resonance. But I wanted to release that thingy finally. 

Anyways your suggestion is a very good hint and! I'll put it on the very top of my todo list 😁

**Comment by Blackjacx** [comment]
Hey @regexident , 

what do you think, better now?

Cheers :-)

**Comment by regexident** [comment]
Perfect! 🤜🏻🤛🏻
